[package]
name = "wtinetwork"
version = "0.1.0"
edition = "2021"

[dependencies]
libp2p = { version = "0.45", features = ["tcp", "yamux", "dns", "gossipsub"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
warp = "0.3"
uuid = "1.0"

